version: '3'
services:
  future:
    container_name: future
    # restart: always
    image: ghcr.io/fugoku/future:dev
    pull_policy: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.future.rule=Host(`fugoku.pro`) && PathPrefix(`/`)"
      - "traefik.http.routers.future.service=future"
      - "traefik.http.services.future.loadbalancer.server.port=3003"
      - "traefik.docker.network=deploy"
      - "traefik.http.routers.future-secure.rule=Host(`fugoku.pro`) && PathPrefix(`/`)"
      - "traefik.http.routers.future-secure.service=future"
      - "traefik.http.services.future-secure.loadbalancer.server.port=3003"
      # - "traefik.http.routers.future-secure.tls=true"
      - "traefik.http.routers.future-secure.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.future.middlewares=redirect-to-https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=1234567890abcdef
      - GITHUB_CLIENT_ID=8ac4d0d2d534e4850ba1
      - GITHUB_CLIENT_SECRET=1f47d0efffb1aea7cab8dfa6479fbae58c2e354b
      - GITHUB_ACCESS_TOKEN=1234567890abcdefghijklmnopqrstuv
      - NEXT_PUBLIC_GITHUB_REDIRECT_URI=http://fugoku.pro
      - SOCIAL_AUTH_REDIRECT_IS_HTTPS=True
      - DATABASE_URL=postgres://default:BDILklmiQ63o@ep-steep-dew-49113896.us-east-1.postgres.vercel-storage.com:5432/verceldb
      - SMTP_FROM=richardokonicha+future@gmail.com
      - POSTMARK_API_TOKEN=a06503e4-0606-49ed-a273-382d3149fd75
      - POSTMARK_SIGN_IN_TEMPLATE=1
      - POSTMARK_ACTIVATION_TEMPLATE=2
      - STRIPE_API_KEY=pk_test_51LoUwzEWUd3V6JZmVoCpFUrBX5ZnB8r2ciEthTnF4CrJuonQPE9O5NYdcLnAWbeFMIwbMQZB6JnAP1paVCFNZRFE00xungTXF4
      - STRIPE_WEBHOOK_SECRET=whsec_d7ac6a81b7ff9ea462cf2dd9274aa79136ef705b2de3c17a24b304377958bc20
      - STRIPE_PRO_MONTHLY_PLAN_ID=price_1N9jVGEWUd3V6JZm4EmJVxdq
      - STRIPE_SECRET_KEY=sk_test_51LoUwzEWUd3V6JZmVROeQUUk5Smd5OpAwiyCmSxoNIZr6s8JrtwKUKQfgeNS1RDh9diCe9Xm0sMpoBZwdvUtBBQj00GhPZTBdO
      - NEXT_PUBLIC_APP_URL=http://fugoku.pro
      - NEXTAUTH_URL=http://fugoku.pro
      - JWT_SECRET=nJKXlFtxf2aZX9yruhtkNwapOW9idIJfg2L2bWedoA==
    networks:
      - coolify-infra
      - fugoku-infra
      - deploy
    ports:
      - 3003:3003
networks:
  coolify-infra:
    external: true
  fugoku-infra:
    external: false
  deploy:
    external: true
