# Base image for building the app
FROM node:lts-buster-slim AS base
RUN apt-get update && apt-get install -y libssl-dev ca-certificates
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
COPY .env .env
COPY prisma prisma
COPY . .
ENV DATABASE_URL="postgres://default:BDILklmiQ63o@ep-steep-dew-49113896.us-east-1.postgres.vercel-storage.com:5432/verceldb"

RUN pnpm install
RUN pnpm run prisma:generate
RUN pnpm build
EXPOSE 3003

# CMD ["pnpm", "run", "d"]
# Production stage
# FROM node:lts-buster-slim AS production
# WORKDIR /app

# # Copy built files from the base stage
# COPY --from=base /app/.next /app/.next
# COPY --from=base /app/public /app/public
# COPY --from=base /app/prisma /app/prisma
# COPY --from=base /app/package.json /app/pnpm-lock.yaml ./

# RUN npm install -g pnpm
# RUN pnpm install


# EXPOSE 3003

# CMD ["pnpm", "start"]
